### ISSUE TITLE
Inspector elements should load faster

### ISSUE THREAD

**Issue by ehenze** [nsynkde/Tilda#25]
... currently slowing down the workflow too much. 
Is there a way to speed this up?
Can they be kept invisible for clips that have been inspected already?

**Comment by jhnnslmk** [comment]
I got in contact with Nathan and described the problem with a very stripped down version of this where value widgets get created in runtime and cause fps drops already.
Waiting for feedback before coming up with a hack. A permanent list with invisible clips with as many clips+values as can happen in a Ctrl+A scenario doesn't sound like an actual solution.
If this can't be adressed from within Elementa properly I'll try to think of something else.

@ehenze 
Out of curiosity, how is this exactly slowing down the workflow?
What do you do to run into situations that often that need to inspect more than 1-3 clips at once and switching between clips / de-selecting and re-selecting them that often?

**Comment by ehenze** [comment]
just feels clunky ... when you want to move clips around you always think twice whether you have to select 'these bad clips that make the interface block for a second'

**Comment by jhnnslmk** [comment]
Gotcha.
Cooked up a patch that shows the behaviour isolated from Tilda and forwarded it to Nathan, waiting for feedback.

**Comment by jhnnslmk** [comment]
Fixed by Dottore, waiting for new release

**Comment by jhnnslmk** [comment]
Addressed in b6125c4a4e5c13f542adee49bbfde451df352a1e
