### ISSUE TITLE
Make editing of Keyframe Clips safer

### ISSUE THREAD

**Issue by ehenze** [nsynkde/Tilda#26]
Right now there are too many wrong clicks that break the user interaction workflow.
Put Editing into its own editing state like for envelope clips, or rather make a global editing state, that can hold an argument as of which clip type is being edited.

At the same time, make sure that not too many clicks are necessary to change values of keyframes. Maybe just keep a modifier key pressed to focus editing only on keyframes (alt isn't used right now in this instance)

**Comment by jhnnslmk** [comment]
Adressed in b6125c4a4e5c13f542adee49bbfde451df352a1e
