### ISSUE TITLE
clicking on a clip to select it should always only select one clip

### ISSUE THREAD

**Issue by ehenze** [nsynkde/Tilda#29]
unless you draw a rect. 
reason: sometimes you move clips on top of each other accidentally, and you want to be able to move clips away from each other again

**Comment by jhnnslmk** [comment]
On it, cleaning up Selection Patch while doing so

**Comment by jhnnslmk** [comment]
Implemented in a9d8a50307c50aaf80fad106f6f05012e95e17ba
