### ISSUE TITLE
Feature Request: Lock state, in dem man nurnoch den Playhead bedienen kann

### ISSUE THREAD

**Issue by ehenze** [nsynkde/Tilda#38]
Über Shortcut / Keykombo zu erreichen. Im Renderer bspw. durch eine Rote Umrandung sichtbar

**Comment by jhnnslmk** [comment]
Gute Idee!
Will do.

**Comment by jhnnslmk** [comment]
Implementiert in 14f0d17295a48702e97d59a9a5c08cea64f770b8.
Hatte zunächst versucht ihn im Automaten zu integrieren, das wurde aber schnell sehr kompliziert, weil der Playhead auf HoverScale/DragPH State lauscht und man sich hier schnell in die Quere kommt.
Ist jetzt eine globale Flag in der Editor Klasse, wird gesetzt über Ctrl+E analog zum Patch Lock in vvvv.
Rote Umrandung zeigt den Zustand an.

Mit dem Modul "StateLock (State)" kann man den Lock State abfragen.

Habe ihn überall dort händisch mit AND reingenommen, wo es Sinn gemacht hat (Copy/Paste, Create Clip/Open Clip/Move/Trim, etc.).
Muss ggfls ergänzt werden, wenn noch etwas auffällt.
