### ISSUE TITLE
Follow vvvv pack folder-structure convention

### ISSUE THREAD

**Issue by jhnnslmk** [nsynkde/Tilda#4]
Hi,
/modules and /vl should be moved as subfolders to a new /nodes/ folder so vvvv will pick those nodes up correctly and show them in the nodebrowser.

Less important, but still note-worthy: I'd propose to keep the root folder as empty as possible, considering "Tilda Example Patch.v4p" a girlpower/example patch and moving it there as well (+ the demo Tilda-Example-Timeline.xml)

Johannes

**Comment by umanema** [comment]
Okidoki
