### ISSUE TITLE
Bezier envelope evaluation returns incorrect results

### ISSUE THREAD

**Issue by idwyr** [nsynkde/Tilda#49]
Hello, as shown in the screenshot, bezier interpolation for envelopes provides incorrect values.

As the timer is trough the point (highlighted in the xml), we should expect an equivalent return value from the node in vvvv. 

![bezier](https://user-images.githubusercontent.com/3972200/65047237-653c8c00-d962-11e9-9f57-9e9323153e3a.png)

Thanks

**Comment by umanema** [comment]
Found the problem. Should fix it in a moment
