### ISSUE TITLE
StackExchange.Redis.RedisConnectionException

### ISSUE THREAD

**Issue by jhnnslmk** [nsynkde/Tilda#5]
When trying to connect:

StackExchange.Redis.RedisConnectionException: It was not possible to connect to the redis server(s). InternalFailure (None, last-recv: 3506) on localhost:6379/Interactive, Idle/Faulted, last: ECHO, origin: ReadFromPipe, outstanding: 0, last-read: 0s ago, last-write: 0s ago, keep-alive: 60s, state: ConnectedEstablished, mgr: 9 of 10 available, in: 0, in-pipe: 3506, out-pipe: 0, last-heartbeat: never, global: 106s ago, v: 2.0.601.3402
   at StackExchange.Redis.ConnectionMultiplexer.ConnectImpl(Object configuration, TextWriter log)
   at Tilda.Sync.TClient.Connect(String& Status, String options)

**Comment by umanema** [comment]
Seems like it's a connection related problem, not the Tilda.Sync. Close for now
