### ISSUE TITLE
Get rid of (deprecated and buggy) jumper category

### ISSUE THREAD

**Issue by vavogt** [nsynkde/Tilda#52]
Instead, the play head jumps to the next jumper clip and then back to its original position

**Comment by vavogt** [comment]
something is overwriting the TC after the jump command. could this have smth to do with the TC synchronization across PCs?

**Comment by vavogt** [comment]
this is probably a hidden feature for most: when adding a clip of category 'jumper' you can jump in between those clips via Shift+Right/Left

**Comment by ehenze** [comment]
Doesn’t seem like a core feature to me and could be deprecated?
Instead something like markers could be introduced. And Stops also don’t need to be a clip - for now it’s just easier to handle them like clips. But maybe the draing should just be different.

**Comment by vavogt** [comment]
Ok, so the new task would be: Get rid of the jumper category. You're right, they were meant to have some sort of 'marker' functionality but were easier to handle as clips..
