### ISSUE TITLE
Coudn't find a suitable serializer for SharpDX.Color4

### ISSUE THREAD

**Issue by vavogt** [nsynkde/Tilda#64]
this error pops up when I am creating a fresh Tilda instance in a virgin patch

**Comment by tebjan** [comment]
because of this? https://vvvv.org/blog/vl-switch-to-xenko-math

**Comment by vavogt** [comment]
hmm... not sure. I'm still on an old alpha. The latest alpha gives me a different error. :-\

**Comment by vavogt** [comment]
seems to be linked to Elementa. When deleting dependencies to Elementa, the error stops

**Comment by vavogt** [comment]
Talked to sebescudie about it. He could reproduce the error and has forwarded this issue to Elias. It doesn't cause any troubles for now, but let's see..
