### ISSUE TITLE
Elementa elements not visible when creating new timeline

### ISSUE THREAD

**Issue by vavogt** [nsynkde/Tilda#65]
When creating a virgin timeline and renderer and creating a keyframe clip, the Elementa buttons are not visible. With some combination of opening the VL patch and resetting (and black magic) they reappear.
Sebescudie seemed to have a similar (or same?) issue and reported it to Elias afaik.

**Comment by umanema** [comment]
It was fixed with new vvvv-beta. I close this issue, but Elementa itself version 1.1.2 is obsolete and we need to either kill it, or moved to a newer version. But newer version obviosly was heavily changed
