### ISSUE TITLE
Automata causing a error on start

### ISSUE THREAD

**Issue by catvvvveasel** [nsynkde/Tilda#71]
https://discourse.vvvv.org/t/vl-tilda/17644

There is an issue with the renderer with latest vvvv release and preview version, drilling down its coming from automata, and index out of range.
Tried with latest previews, and with beta39, the version mention on the frontpage is no longer available. Any ideas of which is the latest working version?

Also checked on another pc with beta38.2 and same error

https://discourse.vvvv.org/uploads/default/original/2X/6/628d671693b94c8280a2d041b1e3bf526b03f0d7.png

https://discourse.vvvv.org/uploads/default/original/2X/b/bc86000ce5ae61ad95a56353ffa5bf3f5c872161.png

**Comment by catvvvveasel** [comment]
Inerestingly, I found the forst release on my laptop, which opens in the latest preview, but has a different error in renderer, in the modify section, but at least does show the timeline

**Comment by umanema** [comment]
Try to fix an issue with 39bf1c4
Check if it helps

**Comment by catvvvveasel** [comment]
I had different errors with that, I had to relink elementa.vl to the included version, I still have some odd errors, but the timeline is now visible and editable, so usable now!
