### ISSUE TITLE
Clips not displayed

### ISSUE THREAD

**Issue by rainerkohlberger** [nsynkde/Tilda#73]
Hi,
Tilda looks great and I would like to try it. However, Clips aren't displayed (sometimes just a for a short moment). Renderer (Tilda) node is displayed red. Version b39x64. What could be wrong?

**Comment by umanema** [comment]
Hey,
most likely it's because of not installed Elementa dependency.

You need to open Renderer by right click. Than click on gray square in the top left corner -> All Documents -> VVVV.Tilda.GUI.vl (should be red) -> Dependences -> right click on Elementa (also red) -> Install

**Comment by rainerkohlberger** [comment]
thanks
